import { Product, User } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'MacBook Pro M2 - 16GB RAM',
    description: 'Barely used MacBook Pro M2, perfect for computer science students.',
    price: 1200,
    category: 'Electronics',
    condition: 'Like New',
    location: 'Main Campus',
    type: 'Item',
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/aeadd02f-bbee-4ff6-9c6f-447e49ed1903/product-laptop-9e11ba81-1783167111377.webp',
    sellerId: 'u1',
    sellerName: 'Alex Smith',
    createdAt: '2023-10-01',
  },
  {
    id: '2',
    name: 'Introduction to Algorithms (CLRS)',
    description: 'The bible of algorithms. Minor highlights on some pages.',
    price: 45,
    category: 'Books',
    condition: 'Good',
    location: 'North Campus',
    type: 'Item',
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/aeadd02f-bbee-4ff6-9c6f-447e49ed1903/product-textbooks-4a6f21a9-1783167113138.webp',
    sellerId: 'u2',
    sellerName: 'Jordan Lee',
    createdAt: '2023-10-05',
  },
  {
    id: '3',
    name: 'Python & React Tutoring',
    description: 'One-on-one tutoring for web development projects.',
    price: 30,
    category: 'Services',
    location: 'West Campus',
    type: 'Service',
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/aeadd02f-bbee-4ff6-9c6f-447e49ed1903/service-tutoring-f34ac662-1783167111678.webp',
    sellerId: 'u1',
    sellerName: 'Alex Smith',
    createdAt: '2023-10-10',
  },
  {
    id: '4',
    name: 'Ergonomic Desk Chair',
    description: 'Very comfortable for long study sessions.',
    price: 80,
    category: 'Furniture',
    condition: 'Good',
    location: 'South Campus',
    type: 'Item',
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/aeadd02f-bbee-4ff6-9c6f-447e49ed1903/product-dorm-decor-8ed1a519-1783167111763.webp',
    sellerId: 'u3',
    sellerName: 'Casey Wong',
    createdAt: '2023-10-12',
  },
  {
    id: '5',
    name: 'Trek Road Bike',
    description: 'Fast and reliable for commuting between campuses.',
    price: 250,
    category: 'Transportation',
    condition: 'Fair',
    location: 'Main Campus',
    type: 'Item',
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/aeadd02f-bbee-4ff6-9c6f-447e49ed1903/product-bike-edd24eb6-1783167110871.webp',
    sellerId: 'u4',
    sellerName: 'Sam Taylor',
    createdAt: '2023-10-15',
  },
];

export const MOCK_USER: User = {
  id: 'u_current',
  name: 'John Doe',
  email: 'john.doe@university.edu',
  isVerified: true,
  mfaEnabled: false,
  referralCode: 'GOONU123',
  referralCount: 3,
  rewards: [
    {
      id: 'r1',
      title: 'Free Delivery',
      description: 'Get free delivery on your next purchase.',
      status: 'Pending',
    },
    {
      id: 'r2',
      title: '$10 Credit',
      description: 'Used for campus bookstore.',
      status: 'Claimed',
      code: 'BOOK10-ABCD',
    },
  ],
};
